title: Dating Edge
description: Online dating strategy and relationship advice
theme: minima
baseurl: "/datingedge"
url: "https://siavashsed.github.io"
markdown: kramdown
permalink: /:year/:month/:day/:title/
show_excerpts: true
minima:
  skin: dark
